version: '3.8'
services:
    app:
        image: mayzura/sisterkuis2
        container_name: php-apache
        depends_on:
            - db
        volumes:
            - ./php/hms:/var/www/html/ (nama-projek diubah sesuai nama folder projek php)
        ports:
            - 8000:80
            network:
                - backend
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ""
	    MYSQL_DATABASE: hotelmanagement
        ports:
            - "3306:3306"
            volumes:
                - db :/var/iib/mysql
                - ./hotelmanagement.sql:/docker-entrypoint-initdb.d/hotelmanagement.sql
                network:
                    - backend

        networks:
            backend:
                name: backend-networks
                ipam: 
                    driver: default
                    config: 
                        -subnet: 172.20.0.0/24

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '3060:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
